### ISSUE TITLE
Visual Studio project cannot open anymore after installing the plugin

### ISSUE THREAD

**Issue by mp9007** [swdotcom/swdc-visualstudio#1]
After installing the plugin, I cannot open a project anymore. I can open Visual Studio, but as soon as I choose a project, visual studio crash. I tried opening different project type to see if it has an influence, but no.

Doesn't have a lot of info about the error too. I looked in the windows event viewer and the only things that could be useful is the error about registry values. See attached image.

I have Visual Studio Professional 2017 - v 15.9.7

Thanks.

![2019-02-22 11_32_26-visualstudiocrasherror](https://user-images.githubusercontent.com/38858370/53256823-cf27d800-3696-11e9-84e5-1c05ee5ac603.png)

**Comment by andrewhli** [comment]
Hi there. Appreciate your note and diagnosis. We're working on this bug today, so until we figure it out, could I ask you to uninstall the plugin? I'll be sure to let you know as soon as it's resolved. We've been working on making our Visual Studio Code extension fully bug-free (if you happen to use VS Code, please check it out!), so we're sorry this bug on Visual Studio escaped us today.

**Comment by mp9007** [comment]
Yes, I did uninstall the plugin for now. Thank you for fast answer :) waiting to add it in visual studio.

**Comment by andrewhli** [comment]
Hi there. We pushed a couple fixes today that our tests show solved this issue. It'd be great if you could install the Visual Studio plugin again. Looking forward to hearing what you think. Thanks!

**Comment by mp9007** [comment]
Sorry about late response, I was sick last week. It still doesn't work. And I cannot get any useful logs like last time... Is there some info about my system that could help you ? 
I'm on windows 10, using visual studio 2017. I have administrator right.

**Comment by mariuszjamro** [comment]
I'm getting the same. Lastest VC (15.9.10) and plugin downloaded from Extensions&Updates.

![error](https://user-images.githubusercontent.com/1384600/55313663-a26e9980-5468-11e9-8a2e-a2e3f23dcbae.png)

**Comment by radaiko** [comment]
I got the same problem with VS (15.9.17) 

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.LegacyNormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.GetFullPathInternal(System.String)
   at System.IO.Directory.InternalCreateDirectoryHelper(System.String, Boolean)
   at System.IO.Directory.CreateDirectory(System.String)
   at SoftwareCo.SoftwareCoUtil.getSoftwareDataDir(Boolean)
   at SoftwareCo.SoftwareCoUtil.getSoftwareSessionFile()
   at SoftwareCo.SoftwareCoUtil.getItem(System.String)
   at SoftwareCo.SoftwareUserSession.GetJwt()
   at SoftwareCo.SoftwareHttpManager+<SendRequestAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at SoftwareCo.SoftwareUserSession+<IsOnlineAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at SoftwareCo.SoftwareCoPackage+<ProcessFetchDailyKpmTimerCallbackAsync>d__41.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```


```
Faulting application name: devenv.exe, version: 15.9.28307.905, time stamp: 0x5d9fb8ad
Faulting module name: KERNELBASE.dll, version: 10.0.17763.737, time stamp: 0xe7ce540a
Exception code: 0xe0434352
Fault offset: 0x0011fd62
Faulting process id: 0x2870
Faulting application start time: 0x01d586aabc45576e
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ff863352-3d51-46a0-bb42-bf5213091c6d
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by brettmstevens7** [comment]
@radaiko We're taking a look at this issue now. If you could also provide your OS version, that would be helpful.

**Comment by radaiko** [comment]
> @radaiko We're taking a look at this issue now. If you could also provide your OS version, that would be helpful.

OS Name:	Microsoft Windows 10 Enterprise
Version:    	10.0.17763 Build 17763

**Comment by EricsG95** [comment]
I am facing the same issues also, cannot launch it on Visual Studio at all for 

Visual Studio 2019.

**Comment by Enderlook** [comment]
Same me. When I open a project everything works fine for a minute and then it suddenly close.
Visual Studio Community 2019 16.4.4.
Windows 10 Pro v1903 OSv18362.356.

**Comment by brettmstevens7** [comment]
Hi @Enderlook @EricsG95 @radaiko @mariuszjamro @mp9007. Sorry for the huge delay here. We finally got around to adding a logging feature. Would you be able to reinstall and try again?

If you encounter the same error when you reinstall, could you send us the log file? It'll be in your `.software` folder in your root user directory.

We'll send you a Cody t-shirt if you help us find the error... thank you all!!!

**Comment by Enderlook** [comment]
Just pointing: link https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-visualstudio from https://github.com/swdotcom/swdc-visualstudio#getting-started has 404 error.

Anyway, the Visual Studio extension searcher does found it.

I didn't see any logging feature (downloaded 0.1.70 version from https://marketplace.visualstudio.com/items?itemName=softwaredotcom.Software).

The error sadly persist :(

This is my log
[Log.txt](https://github.com/swdotcom/swdc-visualstudio/files/4175187/Log.txt)

**Comment by brettmstevens7** [comment]
@Enderlook Thank you, this is very helpful. It looks like there's an issue parsing the JSON in your local `session.json` file in your `.software` folder in your home directory. Would you be able to send us this file at cody@software.com (so we don't reveal any of your sensitive info here)?

**Comment by Enderlook** [comment]
Ok, I'm sending a message with the title `GitHub Repo swdc-visualstudio Issue #1 Bug` with the attached file.
By the way, when I open that file in notepad++, I only see `NUL` characters... may that be the problem?
