### ISSUE TITLE
Hangs on start

### ISSUE THREAD

**Issue by EricChen1248** [swdotcom/swdc-visualstudio#21]
I recently installed code time into my visual studio 2019 community edition. First time running it was fine, however, subsequent starts of the IDE, even after reinstalling the extension will hang the program

The culprit is the CodeTime extension, as uninstalling it will result in the IDE starting normally.

From the output tab, I see it showing
```[CodeTime Info 11:58:53 AM] Initializing Code Time v0.1.54```
right before the hangup.

I can try to provide additional info I can to assist in fixing this bug.

**Comment by brettmstevens7** [comment]
Hi @EricChen1248, we made some performance improvements in the latest version (1.0.8). Can you try this version and let me know if you still experience this issue?

**Comment by vate** [comment]
Happened to me, and solved with the latest update. Thanks!

**Comment by SteinTheRuler** [comment]
I just installed the extension to visual studio 2019 community and it hanged the software right after start up

**Comment by EricChen1248** [comment]
@brettmstevens7 
Nope, issue still occurs. Currently on v2.2.1

**Comment by SteinTheRuler** [comment]
any fix to this?

**Comment by raydixon** [comment]
I just tried again with Visual Studio 2019 Community and Code Time makes it completely unusable. ☹️ 

- Code Time version 2.2.1
- Visual Studio Community 2019 version 16.7.1

@brettmstevens7 Please fix this. I _love_ Code Time with VS Code, but I spend a lot of time in Visual Studio, too, and I want to capture all of it.

**Comment by xavluiz** [comment]
Hi @raydixon, we sincerely apologize. We're in the middle of migrating to 2019 and will update this thread by the beginning of next week when that is available. Thank you for your patience and I apologize for the inconvenience.

Regards.

**Comment by raydixon** [comment]
Thanks, @xavluiz I installed version 2.2.3 with Visual Studio 2019 Community yesterday and, so far, it's working fine. I have noticed three or four times that Visual Studio says that the extension is slowing things down and asks if I want to disable it. I haven't really noticed any slowing and I have just dismissed the alert without disabling it.

**Comment by xavluiz** [comment]
Thank you for the update. We've just recently published another update, v2.2.5, with code analyzing suggestions and general startup performance updates. There are other areas that have been looked at to help prevent CPU consumption. Thanks again!

**Comment by SteinTheRuler** [comment]
I just installed the latest version and VS stopped responding after 15 seconds after loading solution. VS 2019 Community

**Comment by xavluiz** [comment]
Ok, thank you for the update. We'll continue investigating what may be causing this today.
